x-otel-base: &otel-base
  env_file:
    - opentelemetry.properties
  extra_hosts:
    - "host.docker.internal:host-gateway"
  volumes:
    - ../.otel/opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar:ro

name: OpenTelemetry-demo

services:
  service1:
    <<: *otel-base
    image: ceesbos.nl/service1
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - OTEL_SERVICE_NAME=service1
    ports:
      - "8081:8080"

  service2:
    <<: *otel-base
    image: ceesbos.nl/service2
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - OTEL_SERVICE_NAME=service2
    ports:
      - "8082:8080"