x-otel-base: &otel-base
  env_file:
    - opentelemetry.properties
  extra_hosts:
    # host.containers.internal is standard for podman, with this mapping it is also available for docker
    - "host.containers.internal:host-gateway"
  volumes:
    # file is shared with multiple containers, adding 'z' attribute
    - ../.otel/opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar:ro,z

name: OpenTelemetry-demo-app

services:
  alpha:
    <<: *otel-base
    image: ceesbos.nl/alpha
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - OTEL_SERVICE_NAME=alpha
      - SPRING_APPLICATION_NAME=alpha
    ports:
      - "8081:8080"

  beta:
    <<: *otel-base
    image: ceesbos.nl/beta
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - OTEL_SERVICE_NAME=beta
      - SPRING_APPLICATION_NAME=beta
    ports:
      - "8082:8080"