x-otel-base: &otel-base
  env_file:
    - opentelemetry.properties
  extra_hosts:
    # host.containers.internal is standard for podman, with this mapping it is also available for docker
    - "host.containers.internal:host-gateway"
  volumes:
    # file is shared with multiple containers, adding 'z' attribute
    - ../.otel/opentelemetry-javaagent.jar:/app/opentelemetry-javaagent.jar:ro,z

name: OpenTelemetry-demo

services:
  service1:
    <<: *otel-base
    image: ceesbos.nl/service1
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - OTEL_SERVICE_NAME=service1
    ports:
      - "8081:8080"

  service2:
    <<: *otel-base
    image: ceesbos.nl/service2
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - OTEL_SERVICE_NAME=service2
    ports:
      - "8082:8080"